services:
  # DINOv3 기반 매칭 서비스
  matching:
    # 컨테이너 빌드 설정
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: dinov2-matching
    gpus: all
    shm_size: "8g"
    working_dir: /workspace/project
    environment:
      TZ: ${TZ}
      # 매칭 스크립트에서 사용하는 경로
      REPO_DIR: ${REPO_DIR}
      IMG_ROOT: ${IMG_ROOT}
      EMBED_ROOT: ${EMBED_ROOT}
      MATCH_ROOT: ${MATCH_ROOT}
      VIS_ROOT: ${VIS_ROOT}
      VIS_DRAW_POINTS: ${VIS_DRAW_POINTS}
      VIS_POINT_RADIUS: ${VIS_POINT_RADIUS}
      VIS_ALPHA: ${VIS_ALPHA}
      VIS_RANSAC: ${VIS_RANSAC}
      VIS_REPROJ_TH: ${VIS_REPROJ_TH}
      VIS_CONFIDENCE: ${VIS_CONFIDENCE}
      VIS_ITERS: ${VIS_ITERS}
    volumes:
      - ${PROJECT_HOST}:/workspace/project
      - ${CODE_HOST}:/workspace/dinov2
      - ${WEIGHTS_HOST}:/opt/weights:ro
      - ${DATASET_HOST}:/opt/datasets:ro
      - ${EXPORT_HOST}:/exports
    command: bash -lc "sleep infinity"
    stdin_open: true
    tty: true
